/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/components/not_found.component';
const styles_NotFoundComponent:any[] = ([] as any[]);
export const RenderType_NotFoundComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_NotFoundComponent,
  data: {}
}
);
export function View_NotFoundComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['404']))
  ]
  ,(null as any),(null as any));
}
function View_NotFoundComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'not-found',([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
    import0.ɵdid(57344,(null as any),0,import1.NotFoundComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const NotFoundComponentNgFactory:import0.ComponentFactory<import1.NotFoundComponent> = import0.ɵccf('not-found',import1.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvU3RhdFZpZXdlci9hcHAvY29tcG9uZW50cy9ub3RfZm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2plY3RzL1N0YXRWaWV3ZXIvYXBwL2NvbXBvbmVudHMvbm90X2ZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1Byb2plY3RzL1N0YXRWaWV3ZXIvdGVtcGxhdGVzL25vdF9mb3VuZC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1Byb2plY3RzL1N0YXRWaWV3ZXIvYXBwL2NvbXBvbmVudHMvbm90X2ZvdW5kLmNvbXBvbmVudC50cy5Ob3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT40MDQ8L2gxPiIsIjxub3QtZm91bmQ+PC9ub3QtZm91bmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7Ozs7OztJQ0FKO2dCQUFBOzs7SUFBQTs7OyJ9
